baseURL = 'https://tejinder-addminweb.github.io/hugoblog/'
languageCode = 'en-us'
title = 'My Hugo Blog'
theme = 'anank'
publishDir = 'public'

[params]
  theme_color = "#1a365d"
  background_color = "#ffffff"
